# Configure houdini and deadline compatibility
- name: houdini_version_item
  debug:
    var: item
  with_items: "{{ houdini_version_list }}"

- name: Ansible ensure python2.7libs / pythonXlibs dir exists
  file:
    path: "/home/deadlineuser/houdini{{ item.houdini_major_version }}/{{ item.python_libs_folder }}/"
    # strange since this dir doesn't exist
    state: directory
    mode: u=rX,g=rX,o=r
    owner: deadlineuser
    group: syscontrol
    recurse: yes
  become: yes
  with_items: "{{ houdini_version_list }}"
  tags:
  - cloud-install
  - onsite-install

- name: create HoudiniSubmitter dir
  file:
    path: "/home/deadlineuser/Thinkbox/Deadline10/submitters/HoudiniSubmitter/"
    owner: deadlineuser
    group: syscontrol
    state: directory
    mode: u=rwX,g=rwX,o=rX
  become_user: deadlineuser
  become: true

- name: Prepare permissions
  file:
    path: "/var/tmp/submission/Houdini/Client/"
    owner: deadlineuser
    group: syscontrol
    mode: u=rwX,g=rwX,o=rX
    recurse: true
  become: yes
  # delegate_to: ansible_control

- name: Ansible copy directory from tmp on remote server.
  copy:
    src: "/var/tmp/submission/Houdini/Client/{{ item }}"
    remote_src: true
    dest: "/home/deadlineuser/Thinkbox/Deadline10/submitters/HoudiniSubmitter/"
    owner: deadlineuser
    group: syscontrol
  become_user: deadlineuser
  become: true
  with_items:
  - otls
  - soho
  - DeadlineHoudiniClient.py
  - MainMenuCommon.xml
  tags:
  - cloud-install
  - onsite-install
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"

- name: set homedir in xml.
  replace:
    path: /home/deadlineuser/Thinkbox/Deadline10/submitters/HoudiniSubmitter/MainMenuCommon.xml
    regexp: 'HOMEDIR'
    replace: '~/Thinkbox/Deadline10'
  become: yes
  tags:
  - cloud-install
  - onsite-install
  vars:
    ansible_python_interpreter: "{{ package_python_interpreter }}"

- name: set dir permisisons python2.7libs / pythonXlibs
  file:
    path: "/home/deadlineuser/houdini{{ item.houdini_major_version }}/{{ item.python_libs_folder }}/"
    owner: deadlineuser
    group: syscontrol
    state: directory
    mode: u=rwX,g=rwX,o=rX
  become_user: deadlineuser
  become: true
  with_items: "{{ houdini_version_list }}"
  tags:
  - cloud-install
  - onsite-install

- name: Ansible copy CallDeadlineCommand.py to the remote server /opt/Thinkbox/DeadlineRepository10/submission/Houdini/Client/CallDeadlineCommand.py
  copy:
    src: "/var/tmp/submission/Houdini/Client/CallDeadlineCommand.py"
    remote_src: true
    dest: "/home/deadlineuser/houdini{{ item.houdini_major_version }}/{{ item.python_libs_folder }}/"
  become_user: deadlineuser
  become: yes
  with_items: "{{ houdini_version_list }}"
  tags:
  - cloud-install
  - onsite-install

- name: set dir permisisons /opt/Thinkbox/DeadlineRepository10/submission
  file:
    path: "/opt/Thinkbox/DeadlineRepository10/submission/"
    owner: deadlineuser
    group: syscontrol
    state: directory
    mode: u=rwX,g=rwX,o=rX
  # become_user: deadlineuser
  become: true
  tags:
  - cloud-install
  - onsite-install

- name: set dir permisisons /opt/Thinkbox/DeadlineRepository10/submission
  file:
    path: "/opt/Thinkbox/DeadlineRepository10/submission/{{ item }}"
    owner: deadlineuser
    group: syscontrol
    state: directory
    mode: u=rwX,g=rwX,o=rX
  # become_user: deadlineuser
  become: true
  with_items:
  - HServer
  - Houdini
  #- Nuke
  tags:
  - cloud-install
  - onsite-install

- name: Ansible copy submission to the remote server /opt/Thinkbox/DeadlineRepository10/submission/
  copy:
    src: "/var/tmp/submission/{{ item }}"
    remote_src: true
    dest: "/opt/Thinkbox/DeadlineRepository10/submission/"
  # become_user: deadlineuser
  become: yes
  with_items:
  - HServer
  - Houdini
  #- Nuke
  tags:
  - cloud-install
  - onsite-install
# Note: getting a strange permissions issue with copying the nuke subfolder.  upon a second run of the playbook in the shell it is fine.  only the first run in terraform creates the issue.
