- name: configure houdini.env and deadline for items in list
  ansible.builtin.include_tasks: houdini-env-config.yml
  loop: "{{ houdini_version_list }}"
  loop_control:
    loop_var: houdini_version_item
  when: houdini_install_type != "server"
  tags: install_deadline_db

- name: configure houdini and deadline config
  ansible.builtin.include_tasks: houdini-deadline-config.yml
  when: houdini_install_type != "server"
  tags: install_deadline_db