---
# tasks file for roles/houdini_tops_ports_vpn
- debug:
    msg: "Many ports are open for testing.  These should be tightened to minimum necesary advised by SESI"
    
- name: Allow all access from networks to this host for tops.
  ufw:
    rule: allow
    port: "{{ item.port | replace('-',':')}}"
    src: "{{ item.dest }}"
    proto: tcp
  with_items:
  - { port: '49152-65535', dest: "{{ remote_subnet_cidr }}" }
  - { port: '49152-65535', dest: "{{ vpn_cidr }}" }
  - { port: '49152-65535', dest: "{{ private_subnet1 }}" }
  - { port: '49152-65535', dest: "{{ private_subnet2 }}" } 
  - { port: '49152-65535', dest: "{{ public_subnet1 }}" }
  - { port: '49152-65535', dest: "{{ public_subnet2 }}" }
  # # port for tops callback and relay.
  - { port: '1024', dest: "{{ remote_subnet_cidr }}" }
  - { port: '1024', dest: "{{ vpn_cidr }}" }
  - { port: '1024', dest: "{{ private_subnet1 }}" }
  - { port: '1024', dest: "{{ private_subnet2 }}" } 
  - { port: '1024', dest: "{{ public_subnet1 }}" }
  - { port: '1024', dest: "{{ public_subnet2 }}" }

- name: Allow all access from networks to this host for tops.
  ufw:
    rule: allow
    port: "{{ item.port | replace('-',':')}}"
    src: "{{ item.dest }}"
    proto: udp
  with_items:
  - { port: '49152-65535', dest: "{{ remote_subnet_cidr }}" }
  - { port: '49152-65535', dest: "{{ vpn_cidr }}" }
  - { port: '49152-65535', dest: "{{ private_subnet1 }}" }
  - { port: '49152-65535', dest: "{{ private_subnet2 }}" } 
  - { port: '49152-65535', dest: "{{ public_subnet1 }}" }
  - { port: '49152-65535', dest: "{{ public_subnet2 }}" }
  # # port for tops callback and relay.
  - { port: '1024', dest: "{{ remote_subnet_cidr }}" }
  - { port: '1024', dest: "{{ vpn_cidr }}" }
  - { port: '1024', dest: "{{ private_subnet1 }}" }
  - { port: '1024', dest: "{{ private_subnet2 }}" } 
  - { port: '1024', dest: "{{ public_subnet1 }}" }
  - { port: '1024', dest: "{{ public_subnet2 }}" }
