# ---

enforce_henv: false

# the become sudo pass is only relevent for local installation if required on the host specified.
ansible_become_pass: "{{ user_deadlineuser_pw }}"
download_to_dir: /tmp/firehawk
variable_user: "{{ ansible_user }}"
bastionip: "{{ groups['bastionip'][0] }}"
skip_packages: false
houdini_install_type: 'node'
