---
# tasks file for roles/houdini_module

- name: configure packages, permissions and scripts
  include: packages-and-permissions.yml
  tags: install_houdini

- name: install houdini for items in list
  include: houdini-install.yml
  loop: "{{ houdini_version_list }}"
  loop_control:
    loop_var: houdini_version_item
  when: houdini_install_type != "server"
  tags: install_houdini

- name: install houdini server for items in list
  include: houdini-install.yml
  loop: "{{ houdini_license_server_version_list }}"
  loop_control:
    loop_var: houdini_version_item
  when: houdini_install_type == "server"
  tags: install_houdini